# Generated by Django 4.2.6 on 2023-11-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
