# Generated by Django 4.2.6 on 2023-10-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_ref',
        ),
        migrations.AddField(
            model_name='question',
            name='answers_ref',
            field=models.ManyToManyField(blank=True, related_name='question_set', to='quizzes.answer'),
        ),
    ]
