# Generated by Django 4.2.6 on 2023-10-31 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_answers_ref_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='quiz',
        ),
        migrations.AddField(
            model_name='testresult',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='selected_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.answer'),
        ),
    ]
