# Generated by Django 4.2.6 on 2023-10-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_testresult_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(),
        ),
    ]
