# Generated by Django 4.2.6 on 2023-11-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_frequency'),
        ('quizzes', '0003_remove_testresult_correct_answers_and_more'),
    ]

    operations = [
    ]
