# Generated by Django 4.2.6 on 2023-11-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_merge_20231103_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
    ]
