# Generated by Django 4.2.6 on 2023-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_testresult_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
