# Generated by Django 4.2.6 on 2023-10-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_ref',
            field=models.ManyToManyField(blank=True, related_name='question_set', to='quizzes.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
