# Generated by Django 4.2.6 on 2023-11-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='company',
            new_name='associated_company',
        ),
    ]
