# Generated by Django 4.2.6 on 2023-10-30 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_testresult_date_passed_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='date_passed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
