version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh start.sh
    volumes:
      - ./:/Backend/
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis

    volumes:
      - .:/code