version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./Backend/:/usr/src/Backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

