version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh start.sh
    volumes:
      - ./:/Backend/
    ports:
      - 8000:8000
    env_file:
      - .env
