version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/Backend/
    ports:
      - 8000:8000
    env_file:
      - .env.dev


