# Generated by Django 4.2.6 on 2023-10-30 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_companyuserslasttest_averagescores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagescores',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
