# Generated by Django 4.2.6 on 2023-10-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_is_visible_alter_company_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
