# Generated by Django 4.2.6 on 2023-10-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
