# Generated by Django 4.2.6 on 2023-10-23 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0008_alter_company_members_alter_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
