# Generated by Django 4.2.6 on 2023-10-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_request_status'),
        ('companies', '0009_company_admins'),
    ]

    operations = [
    ]
