# Generated by Django 4.2.6 on 2023-10-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_request_status'),
        ('companies', '0010_merge_0009_alter_request_status_0009_company_admins'),
    ]

    operations = [
    ]
